In [ ]:
X_IOLD = [3, 2]
H_IDENTITY = [[1 if i == j else 0 for j in range(len(X_IOLD))] for i in range(len(X_IOLD))]

H_IDENTITY


[[1, 0], [0, 1]]

In [ ]:
# Defina a matriz A (2x2) como uma lista de listas
A = [[1, 2], [3, 4]]

# Defina a matriz B (um vetor com 2 elementos) como uma lista de listas
B = [[5,6]]

# Determine o número de linhas e colunas das matrizes A e B
num_linhas_A = len(A)
num_colunas_A = len(A[0])
num_linhas_B = len(B)
num_colunas_B = len(B[0])

# Verifique se as dimensões das matrizes permitem a multiplicação
if num_colunas_A != num_linhas_B:
    raise ValueError("As dimensões das matrizes não permitem a multiplicação.")

# Inicialize uma matriz vazia para armazenar o resultado da multiplicação
C = []

# Realize a multiplicação matricial manualmente
for i in range(num_linhas_A):
    linha_resultado = []
    for j in range(num_colunas_B):
        produto_ponto = 0
        for k in range(num_colunas_A):
            produto_ponto += A[i][k] * B[k][j]
        linha_resultado.append(produto_ponto)
    C.append(linha_resultado)

# Imprima o resultado
for linha in C:
    print(linha)

TypeError: ignored

In [ ]:
import numpy as np

# Crie uma lista
minha_lista = [1, 2, 3, 4, 5]

# Transponha a lista para um array NumPy bidimensional (uma coluna)
meu_array_transposto = np.array(minha_lista).reshape(-1, 1)

# Imprima o array transposto
meu_array_transposto



array([[1],
       [2],
       [3],
       [4],
       [5]])

In [4]:
import numpy as np

S_K = [-1.0961, -1.8077]
S_K_MINUS1 = [-1, -2]

Y_K = [-2, -4]
Y_K_MINUS1 = [-2.6154, -1.3077]

P = []
Y = []

for J in range(2):
  P.append(S_K[J] - S_K_MINUS1[J])
  Y.append(Y_K[J] - Y_K_MINUS1[J])

P = np.array(P).reshape(-1, 1)
Y = np.array(Y).reshape(-1, 1)
Y

array([[ 0.6154],
       [-2.6923]])

In [5]:
SIGMA = np.dot(P.T, Y)[0,0]
SIGMA

-0.5768692299999999

In [6]:
PP_T = np.dot(P, P.T) * 10
PP_T

array([[ 0.0923521, -0.1848003],
       [-0.1848003,  0.3697929]])

In [32]:
D_Q1 = np.dot(P, P.T)
D_Q1

array([[ 0.00923521, -0.01848003],
       [-0.01848003,  0.03697929]])

In [33]:
TETA = 0
H = np.eye(2)
TAL = np.dot(np.dot(np.transpose(Y), H), Y)
TAL

array([[7.62719645]])

In [34]:
D_Q2 = np.dot(np.dot(H, Y), np.transpose(np.dot(H, Y)))
D_Q2

array([[ 0.37871716, -1.65684142],
       [-1.65684142,  7.24847929]])

In [35]:
D_Q3 = np.dot(np.dot(H, Y), P.T) + np.dot(P, np.transpose(np.dot(H, Y)))
D_Q3

array([[-0.11827988,  0.37707145],
       [ 0.37707145, -1.03545858]])

In [221]:
import numpy as np



In [252]:
x = roulete_wheel_selection([1, 1.5, 3, 0.4], 1)
x

3