In [1]:
from META_TOOLBOX import *

In [2]:
NULL_DIC = None

def MY_FUNCTION(X, NULL_DIC):
    X_0 = X[0]
    X_1 = X[1]
    X_2 = X[2]
    X_3 = X[3]
    X_4 = X[4]
    OF = X_0 ** 2 + X_1 ** 2 + X_2 ** 2 + X_3 ** 2 + X_4 ** 2
    return OF

# Derivatives of the objective function
def MY_FUNCTION_DERIVATIVE(X, NULL_DIC):
    X_0 = X[0]
    X_1 = X[1]
    X_2 = X[2]
    X_3 = X[3]
    X_4 = X[4]
    OF_DIFF_0 = 2 * X_0
    OF_DIFF_1 = 2 * X_1
    OF_DIFF_2 = 2 * X_2
    OF_DIFF_3 = 2 * X_3
    OF_DIFF_4 = 2 * X_4
    OF_DIFF = [OF_DIFF_0, OF_DIFF_1, OF_DIFF_2, OF_DIFF_3, OF_DIFF_4]
    return OF_DIFF

In [3]:
# Load the package
N_POP = 1
D = 5
X_L = [-2, -2, -2, -2, -2]
X_U = [2, 2, 2, 2, 2]
# Initial population
X = META_CO.initial_population_01(N_POP, D, X_L, X_U)
X = np.array([[-1.68992846, -1.85867825, -1.06176198,  1.40726336,  0.11185765]])
X

array([[-1.68992846, -1.85867825, -1.06176198,  1.40726336,  0.11185765]])

In [4]:
METHOD_TYPE = "SD" 


MATEUS = GRADIENT_MOVEMENT(X[0,:], X[0,:], MY_FUNCTION, MY_FUNCTION_DERIVATIVE, METHOD_TYPE, X_L, X_U, NULL_DIC)
MATEUS


[-1.68992846 -1.85867825 -1.06176198  1.40726336  0.11185765] [3.37985692, 3.7173565, 2.12352396, -2.81452672, -0.2237153]
0.5


(array([0., 0., 0., 0., 0.]), 0.0, 1.0, 1)

In [5]:
WANDER = GRADIENT_MOVEMENT(MATEUS, OF_FUNCTION, OF_FUNCTION_DERIVATIVE, NULL_DIC) 
WANDER 

NameError: name 'OF_FUNCTION' is not defined

In [ ]:
SERGIO = GRADIENT_MOVEMENT(WANDER, OF_FUNCTION, OF_FUNCTION_DERIVATIVE, NULL_DIC) 
SERGIO 

X_I_NEW [-4.837052061767386, 4.368796825441044, 4.727383751779685]
X_I [-4.8437644595577725, 4.3762263483376005, 4.734251421229957]
S [6.712397790386564, -7.429522896556619, -6.8676694502721665]


[-4.837052061767386, 4.368796825441044, 4.727383751779685]