In [774]:
from OF_FUNCTION import *
import META_TOOLBOX.META_CO_LIBRARY as META_CO
import numpy as np

In [775]:
N_POP = 5
N_ITER = 100
X_L = [-10, -10, -10]
X_U = [10, 10, 10]
D = 3
NULL_DIC = None

# Initial population

In [776]:
X = META_CO.initial_population_01(N_POP, D, X_L, X_U)
X

array([[ 7.90032255,  4.64520052,  0.05954577],
       [-2.0472998 ,  5.26538799,  0.18463867],
       [ 3.35524016, -0.10622866, -4.2489343 ],
       [ 7.22147346,  8.74528814, -5.86088809],
       [-4.97411175, -5.80439184,  6.53470834]])

# OF and FITNESS

In [777]:
OF = np.zeros((N_POP, 1))
FIT = np.zeros((N_POP, 1))
for I in range(N_POP):
    OF[I, 0] = MY_FUNCTION(X[I,:], NULL_DIC)
    FIT[I, 0] = META_CO.fit_value(OF[I, 0])

In [778]:
OF

array([[ 83.99652991],
       [ 31.94983862],
       [ 29.32236375],
       [162.97975282],
       [101.13516548]])

In [779]:
FIT

array([[0.01176519],
       [0.03034916],
       [0.03297896],
       [0.00609831],
       [0.00979095]])

In [780]:
for J in range(N_POP):
    SELECTED_POS = ROULETE_WHEEL_SELECTION(FIT, N_POP, int(J))
    print(J, SELECTED_POS)
    
    print(X[J, :])    

0 2
[ 6.37028429  0.16387692 -0.73387952]


IndexError: list assignment index out of range

In [ ]:
SELECTED_POS = ROULETE_WHEEL_SELECTION(FIT, N_POP, 1)
SELECTED_POS

2

In [ ]:

print(X, OF, FIT, NEOF)

[-6.79451817 -3.66048976 -1.91943976] 63.248911384201854 0.01556446605017326 1


# Internal Functions

# Theory



In [23]:
a = [0, 1, 2, 3 , 4, 5, 6, 7, 8, 9]
b = [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

RESULT = LINEAR_CROSSOVER(FATHER1=a, FATHER_2=b)

#RESULT = BLX_ALPHA(FATHER1=a, FATHER_2=b)
print(RESULT)


[2.293902597834955, 7.159428610631746, -1.7239476719833693, 5.210799476463794, 6.98212643559399, 4.601854492958886, -4.009574321978727, -1.0718073241382777, 1.0971820804150965, -1.1057709418316026]
